-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A, (
    SELECT MAX(PRICE) AS M_PRICE, CATEGORY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS B
WHERE B.M_PRICE = A.PRICE AND B.CATEGORY = A.CATEGORY
ORDER BY M_PRICE DESC;
