-- 4번 문제
-- write your code in PostgreSQL 9.4
SELECT S.NAME
FROM (SELECT ND.NAME, SUM(ND.DURATION) SUMVALUE
    FROM (SELECT P.NAME, C.DURATION
          FROM PHONES P LEFT OUTER JOIN CALLS C
          ON P.PHONE_NUMBER = C.CALLER OR P.PHONE_NUMBER = C.CALLEE) ND
    GROUP BY NAME) S
WHERE S.SUMVALUE >= 10
ORDER BY 1;